const {test,before,after}=require('node:test');
const assert=require('node:assert/strict');
const http=require('node:http');
const fs=require('node:fs');
const path=require('node:path');
const {chromium}=require('playwright');
let browser,server,url;
const root='11111111111111111111111111111111',crime='22222222222222222222222222222222',sport='33333333333333333333333333333333';
const a='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',b='bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',c='cccccccccccccccccccccccccccccccc';
function fixture(){return {groups:[{Id:crime,Name:'Crime',ChannelCount:2},{Id:sport,Name:'Sport',ChannelCount:2}],refs:{[crime]:[a,b],[sport]:[a,c]},prefs:{HiddenGroupIds:[],DefaultGroupId:crime,DefaultView:'guide',Zoom:5,RememberLastView:false,LastGroupId:null,LastView:'guide'},requests:[],fail:false,delay:false};}
const channels=[{Id:a,Name:'RTL Crime',ChannelNumber:'127'},{Id:b,Name:'Investigation',ChannelNumber:'7'},{Id:c,Name:'Sport',ChannelNumber:'58'}];
let fixtures=new Map();
const shell=`<!doctype html><html><head><meta charset="utf-8"><title>Jellyfin groups regression</title><link rel="stylesheet" href="/LiveTvGroups/client.css"><style>body{background:#101010;color:#eee;font:16px Arial;margin:0}header{padding:20px}.page{padding:20px}.hide{display:none}</style></head><body><header><a href="#/list?parentId=${root}&serverId=server">Live-TV Gruppen</a> <a href="#/livetv">Live TV</a> <a href="#/userpluginsettings.html?pageUrl=/LiveTvGroups/page.html">Plugin Pages</a></header><div class="page libraryPage"><div class="native-content">Original content</div></div><script>
window.ApiClient={accessToken:()=>new URLSearchParams(location.search).get('fixture'),getCurrentUserId:()=> 'user',serverId:()=> 'server',deviceId:()=> 'device',getUrl:(p,q)=> '/'+p+(q?'?'+new URLSearchParams(q):''),getScaledImageUrl:()=>'',getJSON:async u=>{const r=await fetch(u,{headers:{Authorization:'MediaBrowser Token="'+new URLSearchParams(location.search).get('fixture')+'"'}});return r.json();},ajax:async()=>[]};
function native(){const own=location.hash.includes('parentId=${root}');document.querySelector('.libraryPage').classList.toggle('hide',location.hash.startsWith('#/details'));const target=document.querySelector('.native-content');target.textContent=location.hash.startsWith('#/details')?'Details':own?'Original group folder':'Original Live TV: all 432 channels';if(location.hash.startsWith('#/livetv'))fetch('/LiveTv/Channels');if(location.hash.startsWith('#/userpluginsettings'))fetch('/LiveTvGroups/page.html').then(r=>r.text()).then(html=>target.append(document.createRange().createContextualFragment(html)));document.dispatchEvent(new Event('viewshow'));}window.addEventListener('hashchange',native);native();</script><script src="/LiveTvGroups/client.js"></script></body></html>`;
before(async()=>{
 server=http.createServer(async(req,res)=>{const key=(req.headers.authorization||'').match(/Token="([^"]+)"/)?.[1];const fixtureId=new URL(req.url,'http://local').searchParams.get('fixture');const f=fixtures.get(key||fixtureId);const u=new URL(req.url,'http://local');const send=(value,status=200)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(status===204?'':JSON.stringify(value));};
 if(u.pathname.endsWith('client.js')||u.pathname.endsWith('client.css')){res.setHeader('Content-Type',u.pathname.endsWith('.js')?'application/javascript':'text/css');res.end(fs.readFileSync(path.join(__dirname,'../../src/Jellyfin.Plugin.LiveTvGroups/Web',path.basename(u.pathname))));return;}
 if(u.pathname.endsWith('/page.html')){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(fs.readFileSync(path.join(__dirname,'../../src/Jellyfin.Plugin.LiveTvGroups/Web/page.html')));return;}
 if(u.pathname==='/'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(shell);return;}
 if(u.pathname==='/LiveTv/Channels'){send({Items:Array.from({length:432},(_,i)=>({Id:i}))});return;}
 if(!f){send({},401);return;}f.requests.push(req.method+' '+u.pathname);let data='';for await(const chunk of req)data+=chunk;const body=data?JSON.parse(data):null;
 if(u.pathname.endsWith('/Entry')){send({ChannelId:root,Version:'0.3.1.0'});return;}
 if(u.pathname.endsWith('/Preferences')){if(req.method==='PUT'){f.prefs=body;send(null,204);}else send(f.prefs);return;}
 if(u.pathname.endsWith('/AvailableChannels')){send({Items:channels});return;}
 if(u.pathname==='/LiveTvGroups/Groups'){if(req.method==='POST'){const g={Id:'44444444444444444444444444444444',Name:body.Name,ChannelCount:0};f.groups.push(g);f.refs[g.Id]=[];send(g);}else send(f.groups);return;}
 const match=u.pathname.match(/\/Groups\/([^/]+)(?:\/(Channels|Order))?$/);
 if(match){const gid=match[1],g=f.groups.find(g=>g.Id===gid);if(req.method==='DELETE'){f.groups=f.groups.filter(g=>g.Id!==gid);send(null,204);}else if(match[2]==='Channels'){f.refs[gid]=body;g.ChannelCount=body.length;send(null,204);}else if(g){g.Name=body.Name;send(null,204);}else send({},404);return;}
 const ids=[...new Set(u.searchParams.getAll('groupIds').flatMap(g=>f.refs[g]||[]))],scope=ids.map(id=>channels.find(c=>c.Id===id)).filter(Boolean);
 if(u.pathname.endsWith('/Channels')){send({Items:scope});return;}
 if(u.pathname.endsWith('/Guide')){f.lastGuide={start:u.searchParams.get('start'),end:u.searchParams.get('end')};if(f.fail){f.fail=false;send('Guide unavailable',500);return;}if(f.delay&&u.searchParams.getAll('groupIds').includes(sport))await new Promise(r=>setTimeout(r,300));const start=u.searchParams.get('start'),end=u.searchParams.get('end');send({Start:start,End:end,Channels:scope,Programs:scope.filter(c=>c.Id!==b).map((c,i)=>({Id:c.Id,ChannelId:c.Id,Name:c.Name+' program',EpisodeTitle:'Episode',StartDate:new Date(Date.parse(start)-6*3600000).toISOString(),EndDate:new Date(Date.parse(end)+6*3600000).toISOString()})),MissingChannelCount:0,InvalidProgramCount:0});return;}
 send({},404);
 });await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({headless:true,...(process.env.LTVG_BROWSER_CHANNEL?{channel:process.env.LTVG_BROWSER_CHANNEL}:{})});
});
after(async()=>{await browser?.close();server?.close();});
async function open(t,viewport={width:1440,height:1000},at=null){const key=Math.random().toString(36).slice(2),f=fixture();fixtures.set(key,f);const context=await browser.newContext({viewport,timezoneId:'Europe/Vienna'});const page=await context.newPage();if(at)await page.clock.install({time:new Date(at)});const errors=[];page.on('pageerror',e=>errors.push(e.message));t.after(async()=>{if(t.passed===false)console.log(await page.locator('#ltvg-page').innerText().catch(()=>''));await context.close();fixtures.delete(key);assert.deepEqual(errors,[]);});await page.goto(url+'/?fixture='+key+'#/list?parentId='+root+'&serverId=server');await page.locator('.ltvg-guide-prog').first().waitFor();if(process.env.LTVG_QA_DIR)await page.screenshot({path:path.join(process.env.LTVG_QA_DIR,viewport.width<500?'groups-mobile.png':'groups-desktop.png')});return {page,f};}
test('own guide, details and return preserve group and scroll; original Live TV stays intact',async t=>{const {page,f}=await open(t);assert.equal(await page.locator('.ltvg-guide-row').count(),3);await page.locator('.ltvg-guide-scroll').evaluate(e=>e.scrollLeft=450);await page.locator('.ltvg-guide-caption').first().click();await page.waitForURL(/#\/details\?/) ;await page.locator('#ltvg-page').waitFor({state:'detached'});await page.goBack();await page.locator('.ltvg-guide-prog').first().waitFor();assert.match(page.url(),/group=/);assert.equal(await page.locator('.ltvg-guide-scroll').evaluate(e=>e.scrollLeft),450);await page.getByRole('link',{name:'Live TV',exact:true}).click();await page.locator('#ltvg-page').waitFor({state:'detached'});assert.equal(await page.locator('[data-ltvg-host]').count(),0);assert.match(await page.locator('.native-content').innerText(),/all 432/);assert.equal(await page.locator('#ltvg-open-button').count(),0);assert.ok(f.requests.every(r=>!r.includes('GuideFilter')));});
test('visible groups and zoom persist; union deduplicates channels',async t=>{const {page,f}=await open(t);await page.getByLabel('Gruppe',{exact:true}).selectOption('all');await page.waitForFunction(()=>document.querySelectorAll('.ltvg-guide-row').length===4);await page.getByRole('button',{name:'Einstellungen',exact:true}).click();await page.locator('[data-group="'+sport+'"]').uncheck();await page.locator('[name="zoom"]').selectOption('8');await page.getByRole('button',{name:'Speichern',exact:true}).click();await page.locator('#ltvg-modal').waitFor({state:'detached'});assert.deepEqual(f.prefs.HiddenGroupIds,[sport]);assert.equal(f.prefs.Zoom,8);assert.equal(await page.getByLabel('Gruppe',{exact:true}).locator('option').count(),2);await page.reload();await page.locator('.ltvg-guide-prog').first().waitFor();assert.equal(await page.getByLabel('Zoom',{exact:true}).inputValue(),'8');});
test('sender search hides nonmatches and selected-only filter works',async t=>{const {page}=await open(t);await page.getByLabel('Ansicht',{exact:true}).selectOption('channels');await page.getByRole('button',{name:'Sender auswählen',exact:true}).click();await page.getByRole('button',{name:'Speichern',exact:true}).waitFor({state:'visible'});await page.getByRole('searchbox').fill('Crime');await page.waitForFunction(()=>document.querySelector('.ltvg-picker-count').textContent.includes('1 Treffer'));assert.equal(await page.locator('.ltvg-picker .ltvg-picker-row:visible').count(),1);await page.getByRole('searchbox').fill('');await page.getByLabel('Nur ausgewählte Sender').check();assert.equal(await page.locator('.ltvg-picker .ltvg-picker-row:visible').count(),2);await page.getByRole('button',{name:'Abbrechen'}).click();});
test('latest group wins delayed requests, failure can be retried',async t=>{const {page,f}=await open(t);f.delay=true;await page.getByLabel('Gruppe',{exact:true}).selectOption(sport);await page.getByLabel('Gruppe',{exact:true}).selectOption(crime);await page.waitForTimeout(450);assert.equal(await page.locator('.ltvg-guide-row').count(),3);f.fail=true;await page.getByRole('button',{name:'Aktualisieren',exact:true}).click();await page.locator('.ltvg-error:not([hidden])').waitFor();await page.getByRole('button',{name:'Erneut versuchen'}).click();await page.locator('.ltvg-error').waitFor({state:'hidden'});await page.locator('.ltvg-guide-prog').first().waitFor();});
test('mobile scroll keeps program labels readable; date navigation works',async t=>{const {page}=await open(t,{width:390,height:844});await page.locator('.ltvg-guide-scroll').evaluate(e=>e.scrollLeft=600);await page.waitForTimeout(50);const visible=await page.locator('.ltvg-guide-caption').first().evaluate(e=>{const c=e.getBoundingClientRect(),p=e.closest('.ltvg-guide-scroll').getBoundingClientRect();return c.left>=p.left&&c.left<p.right&&c.width>80;});assert.equal(visible,true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.getByRole('button',{name:'Heute Abend',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[data-control="time"]')?.value==='18:00');await page.getByRole('button',{name:'Jetzt',exact:true}).click();await page.locator('.ltvg-guide-prog').first().waitFor();assert.ok(!page.url().includes('start='));});
test('create, select senders, rename, reorder and delete group',async t=>{const {page,f}=await open(t);await page.getByRole('button',{name:'Gruppen verwalten',exact:true}).click();await page.getByRole('button',{name:'Neue Gruppe',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('Test');await page.getByRole('button',{name:'Speichern',exact:true}).click();await page.getByRole('button',{name:'Sender auswählen',exact:true}).click();await page.locator('.ltvg-picker input[value="'+a+'"]').check();await page.locator('.ltvg-picker input[value="'+c+'"]').check();await page.getByRole('button',{name:'Speichern',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.ltvg-channel-card').length===2);await page.getByRole('button',{name:'Reihenfolge ändern'}).click();await page.getByRole('button',{name:'Sender nach oben'}).nth(1).click();await page.waitForFunction(()=>document.querySelector('.ltvg-channel-card').dataset.id===''+ 'cccccccccccccccccccccccccccccccc');assert.equal(f.refs['44444444444444444444444444444444'][0],c);await page.getByRole('button',{name:'Gruppen verwalten',exact:true}).click();const card=page.locator('.ltvg-group-card').filter({hasText:'Test'});await card.getByRole('button',{name:'Umbenennen'}).click();await page.getByLabel('Name',{exact:true}).fill('Renamed');await page.getByRole('button',{name:'Speichern',exact:true}).click();await page.locator('.ltvg-group-card').filter({hasText:'Renamed'}).getByRole('button',{name:'Löschen',exact:true}).click();await page.locator('#ltvg-modal').getByRole('button',{name:'Löschen',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.ltvg-group-card').length===2);assert.equal(f.groups.length,2);});

test('calendar navigation crosses DST correctly; programs use current time after future guide',async t=>{
 const {page,f}=await open(t,{width:1440,height:1000},'2026-10-24T16:00:00Z');
 await page.getByRole('button',{name:'Heute Abend',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('[data-control="time"]')?.value==='18:00');
 const saturday=Date.parse(f.lastGuide.start);
 await page.locator('[data-action="day"]').nth(1).click();
 await page.waitForFunction(()=>document.querySelector('[data-control="date"]')?.value==='2026-10-25');
 assert.equal((Date.parse(f.lastGuide.start)-saturday)/3600000,25);
 await page.getByLabel('Ansicht',{exact:true}).selectOption('programs');
 await page.locator('.ltvg-program-rail').first().waitFor();
 assert.ok(Math.abs(Date.parse(f.lastGuide.start)-Date.parse('2026-10-24T16:00:00Z'))<3600000);
 assert.ok(f.requests.every(r=>!r.includes('/LiveTv/Programs')));
});

test('optional Plugin Pages fragment opens the same independent groups route',async t=>{
 const {page}=await open(t);
 await page.getByRole('link',{name:'Plugin Pages',exact:true}).click();
 await page.waitForURL(/#\/list\?parentId=/);
 await page.locator('.ltvg-guide-prog').first().waitFor();
 assert.match(page.url(),/liveTvGroups=1/);
 assert.equal(await page.locator('[data-ltvg-host]').count(),1);
});
